import sqlite3
c = sqlite3.connect('screener.db')
r = c.execute("SELECT MAX(date) FROM bars WHERE timeframe='1Day'").fetchone()
print('Latest US bar date:', r[0])
r2 = c.execute("SELECT COUNT(*) FROM (SELECT symbol, MAX(date) as md FROM bars WHERE timeframe='1Day' GROUP BY symbol HAVING md >= '2026-07-17')").fetchone()
print('Symbols with bars >= Jul 17:', r2[0])
r3 = c.execute("SELECT COUNT(*) FROM assets WHERE status='active' AND tradable=1 AND COALESCE(exchange,'') NOT IN ('OTC','')").fetchone()
print('Active tradable non-OTC symbols:', r3[0])
r4 = c.execute("SELECT COUNT(DISTINCT symbol) FROM bars WHERE timeframe='1Day'").fetchone()
print('Symbols with any bars:', r4[0])
from datetime import date, timedelta
d = date.today() - timedelta(days=1)
while d.weekday() >= 5: d -= timedelta(days=1)
print('Cutoff date:', d)
r5 = c.execute("SELECT COUNT(*) FROM (SELECT a.symbol, MAX(b.date) as md FROM assets a JOIN bars b ON a.symbol=b.symbol AND b.timeframe='1Day' WHERE a.status='active' AND a.tradable=1 AND COALESCE(a.exchange,'') NOT IN ('OTC','') GROUP BY a.symbol HAVING md >= ?)", (str(d),)).fetchone()
print('Symbols up to date (>= cutoff):', r5[0])
# Check the 182 new IPOs - do they have ANY bars?
r6 = c.execute("SELECT COUNT(*) FROM assets WHERE status='active' AND tradable=1 AND COALESCE(exchange,'') NOT IN ('OTC','') AND symbol NOT IN (SELECT DISTINCT symbol FROM bars WHERE timeframe='1Day')").fetchone()
print('Active symbols with ZERO bars:', r6[0])
c.close()
