import sqlite3
c = sqlite3.connect('screener.db')
r = c.execute("SELECT COUNT(*) FROM historical_screener").fetchone()
print('total hist rows:', r[0])
r2 = c.execute("SELECT COUNT(*) FROM historical_screener WHERE date >= '2024-07-23' AND date <= '2026-07-21'").fetchone()
print('last 500 dates:', r2[0])
r3 = c.execute("SELECT COUNT(DISTINCT symbol) FROM historical_screener WHERE date >= '2024-07-23'").fetchone()
print('symbols with recent data:', r3[0])
r4 = c.execute("SELECT symbol, COUNT(*) FROM historical_screener GROUP BY symbol LIMIT 5").fetchall()
print('sample symbol counts:', r4)
c.close()
