import sqlite3
c = sqlite3.connect('C:/Users/Admin/Desktop/stock test/open code v5 claude prompt/india.db', timeout=10)
c.execute('PRAGMA busy_timeout=5000')
r = c.execute("SELECT COUNT(*), MAX(date) FROM historical_screener").fetchone()
print(f"INDIA hist_screener: {r[0]} rows, max date: {r[1]}")
r = c.execute("SELECT COUNT(*) FROM historical_screener WHERE date = '2026-07-24'").fetchone()
print(f"Rows on 2026-07-24: {r[0]}")
r = c.execute("SELECT COUNT(*), MAX(date) FROM bars WHERE timeframe='1Day'").fetchone()
print(f"INDIA bars: {r[0]} rows, max date: {r[1]}")
r = c.execute("SELECT MAX(last_updated) FROM stats").fetchone()
print(f"INDIA stats updated: {r[0]}")
r = c.execute("SELECT SUBSTR(string_id,1,2) as t, COUNT(*) FROM string_universe GROUP BY t").fetchall()
print(f"INDIA strings: {dict(r)}")
r = c.execute("SELECT COUNT(*) FROM string_screener_metrics").fetchone()
print(f"INDIA string metrics: {r[0]}")
r = c.execute("SELECT COUNT(*), MAX(date) FROM historical_string_screener").fetchone()
print(f"INDIA string historical: {r[0]} rows, max date: {r[1]}")
c.close()
